### ISSUE TITLE
Please let me know how to use this model.

### ISSUE THREAD

**Issue by PulkitVini** [rupinder1133/ln2sqlmodule#1]
Hi ,

Can you please provide proper steps how to use this module using jupyter notebook. Any help would be really commendable.

**Comment by rupinder1133** [comment]
My apologies for delayed reply.
I don't use jupyter as such but would try it out and let you know.

**Comment by rupinder1133** [comment]
Hey, I have published the package to PyPi so now you can easily use it in jupyter notebook, just install it by running:
```
pip install ln2sqlmodule
```

**Comment by KhouloudBt** [comment]
hi i wonna die baliz

**Comment by KhouloudBt** [comment]
fuck me i'm dump just like this bitch next to me
