### ISSUE TITLE
import ln2sqlmodule

### ISSUE THREAD

**Issue by VenkatK9** [rupinder1133/ln2sqlmodule#3]
Hello Rupinder,

I am unable to use import ln2sqlmodule. I have downloaded the file and extracted it. I tried it in pycharm as well. the get queries are not working as well as they are throwing syntax errors which I can fix but the only module I find is ln2sql from python library.

can you please help with this issue.

**Comment by rupinder1133** [comment]
Hi Venkat,
My apologies for late reply. I have published this as a package to PyPi for easier use. kindly install using `pip` and use as usual.

You can install it by running:
```
pip install ln2sqlmodule
```
